server:
  port: 8080

spring:
  application:
    name: Product search
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: docker-cluster

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

app:
  elasticsearch:
    cluster-name: docker-cluster
    cluster-nodes: localhost:9300
    index-name: products
    type-name: _doc
    templates: